apiVersion: v1
kind: Service
metadata:
  name: kafka-kafdrop-service
  namespace: kafka-dev
  labels:
    app: kafka-kafdrop
spec:
  ports:
    - protocol: "TCP"
      port: 9000
      targetPort: 9000
  selector:
    app: kafka-kafdrop
  type: ClusterIP
