apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: kafka-dev
spec:
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
  selector:
    app: schema-registry
  type: ClusterIP
